### ISSUE TITLE
Can't we have the nispor python bindings available in Pypi ?

### ISSUE THREAD

**Issue by sreerajkksd** [nispor/nispor#150]
I remember seeing an older version of nispor on pypi, but I don't see it now. Can't we have the nispor python package on pypi ?

**Comment by cathay4t** [comment]
@sreerajkksd I failed to find a good way to compile nispor rust code or ask user to install `nispor-libs` during `python setup.py build` stage. So we remove it.

Personally, I dislike pip, so I would suggest you to use `make install` of nispor tarball or use OS shipped rpm.

**Comment by cathay4t** [comment]
Closing as won't fix.
