### ISSUE TITLE
Add support TUN/TAP

### ISSUE THREAD

**Issue by cathay4t** [nispor/nispor#16]
The rust-netlink is providing `nlas::Info::Data` for `IFLA_INFO_DATA` for TUN/TAP interface as a `Vec<u8>` .

To parse that raw u8 array, you need to read the linux kernel code `drivers/net/tun.c` for function `tun_fill_info()`.

The commit 978a8be91f8e82f7b0143062d4f9f05bfa014381 could be a good example.

**Comment by cathay4t** [comment]
This might be little bit challenging considering it require understanding of kernel netlink code.

**Comment by cathay4t** [comment]
Beniamino is working on this. Please check before starting work.

**Comment by ffmancera** [comment]
I think this has been done by https://github.com/nispor/nispor/pull/20.
