### ISSUE TITLE
Use `NlasIterator` and `NlaBuffer` instread of parsing by ourselves

### ISSUE THREAD

**Issue by cathay4t** [nispor/nispor#17]
We are using `parse_nla_header` in these files:

- [ ] `src/lib/netlink/bond.rs`

- [ ] `src/lib/netlink/bridge_port.rs`

- [ ] `src/lib/netlink/bridge_vlan.rs`

- [ ] `src/lib/netlink/vxlan.rs`

For parsing netlink message or netlink nested message using old C-style memory hack, we should switch to `NlasIterator` and `NlaBuffer`.

You may take `src/lib/ifaces/sriov.rs` function `get_sriov_info()` as example using  `NlasIterator`.
You may take `src/lib/ifaces/vrf.rs` function `get_vrf_info()` as example of using `NlaBuffer`.

**Comment by qinqon** [comment]
Hi, I may try to fix this, it's ok ?

**Comment by qinqon** [comment]
Adding here some usufull doc:
- https://olegkutkov.me/2018/02/14/monitoring-linux-networking-state-using-netlink/
- https://docs.pyroute2.org/netlink.html
- https://man7.org/linux/man-pages/man7/netlink.7.html
- https://docs.rs/netlink-sys/0.0.1/netlink_sys/index.html

**Comment by qinqon** [comment]
@cathay4t created a draft with just one replacement of `parse_nla_header` at `bond.rs`, let me know if is the way to go.

**Comment by cathay4t** [comment]
@qinqon Yes. It is. I have assigned this issue. Let me know if you need help.
