### ISSUE TITLE
Change the bond options from hashmap to struct members.

### ISSUE THREAD

**Issue by cathay4t** [nispor/nispor#25]
Allowing arbitrary bond options in hashmap is not a good API.
Should use `Option<>` to hide the invalid options.

**Comment by robgc** [comment]
@cathay4t @ffmancera I would like to work on this issue.

**Comment by ffmancera** [comment]
Sure!

**Comment by ffmancera** [comment]
Oops it seems there has been a little bit of overlap on this issue. https://github.com/nispor/nispor/commit/6ebf64d4ee6f45ef0015212d4b917fe9054ae6c1 @cathay4t
