### ISSUE TITLE
Convert all the `[ ]` access to `get()`.

### ISSUE THREAD

**Issue by cathay4t** [nispor/nispor#55]
The `[]` might crash when out of index, but as a library, we should never crashes.

Please change it to `get()` and handle the errors.

**Comment by YtvwlD** [comment]
Oh well, I didn't know that GitHub was going to put this here before I had opened a PR.

I've been trying to get this done and I think I've got it done for the `ifaces` module, but the `netlink` module has many `[]` that might panic – every function in `netlink/nla.rs` is a candidate for returning a `Result` that has to be handled somewhere. Would this make sense?
(I'm happy to do that if it does, but I figured I should probably ask beforehand.)

**Comment by ffmancera** [comment]
> Oh well, I didn't know that GitHub was going to put this here before I had opened a PR.
> 
> I've been trying to get this done and I think I've got it done for the `ifaces` module, but the `netlink` module has many `[]` that might panic – every function in `netlink/nla.rs` is a candidate for returning a `Result` that has to be handled somewhere. Would this make sense?
> (I'm happy to do that if it does, but I figured I should probably ask beforehand.)

Yes, it should be done. We should handle all the errors possible :-). Sorry for the late answer :(

**Comment by ffmancera** [comment]
@YtvwlD This is 1.0_must which means we need this done by tomorrow. How are you doing? If that is too much to ask, I will cherry-pick your commits and include them in my PR if you don't mind.
